spring:
  config:
    name: shop
  session:
    timeout: 20m  # Время жизни сессии
  datasource:
    url: jdbc:postgresql://localhost:5432/KoreanShop
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql:
  security:
    session:
      creation-policy: always

server:
  port: 8976
#  error:
#    whitelabel:
#      enabled: false
#    path: /error
  servlet:
    session:
      timeout: 20m


