-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.brand_model
(
    id uuid NOT NULL,
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT brand_model_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.category_model
(
    id uuid NOT NULL,
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT category_model_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customer_model
(
    id uuid NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT customer_model_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_model
(
    id uuid NOT NULL,
    order_date timestamp(6) without time zone NOT NULL,
    customer_id uuid NOT NULL,
    CONSTRAINT order_model_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_products
(
    order_id uuid NOT NULL,
    product_id uuid NOT NULL,
    CONSTRAINT order_products_pkey PRIMARY KEY (order_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.product_model
(
    id uuid NOT NULL,
    date_order timestamp(6) without time zone,
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    image character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    price double precision NOT NULL,
    quantity integer NOT NULL,
    brand_id uuid,
    category_id uuid,
    supplier_id uuid,
    CONSTRAINT product_model_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_tags
(
    product_id uuid NOT NULL,
    tag_id uuid NOT NULL,
    CONSTRAINT product_tags_pkey PRIMARY KEY (product_id, tag_id)
);

CREATE TABLE IF NOT EXISTS public.review_model
(
    id uuid NOT NULL,
    comment character varying(255) COLLATE pg_catalog."default",
    rating integer NOT NULL,
    customer_id uuid NOT NULL,
    product_id uuid NOT NULL,
    CONSTRAINT review_model_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.supplier_model
(
    id uuid NOT NULL,
    address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    contact_info character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT supplier_model_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tag_model
(
    id uuid NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tag_model_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_model
(
    id_user bigint NOT NULL,
    active boolean NOT NULL,
    password character varying(255) COLLATE pg_catalog."default",
    username character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT user_model_pkey PRIMARY KEY (id_user)
);

CREATE TABLE IF NOT EXISTS public.user_role
(
    user_id bigint NOT NULL,
    roles character varying(255) COLLATE pg_catalog."default"
);

ALTER TABLE IF EXISTS public.order_model
    ADD CONSTRAINT fk95k618182n488qohwr38kl1ta FOREIGN KEY (customer_id)
    REFERENCES public.customer_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_products
    ADD CONSTRAINT fkkoy1ac90tpykaay87l0s07aun FOREIGN KEY (order_id)
    REFERENCES public.order_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.order_products
    ADD CONSTRAINT fkn6n7giu1huvbxrwt3dpg11dou FOREIGN KEY (product_id)
    REFERENCES public.product_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product_model
    ADD CONSTRAINT fk1gl1l4w5peiofv67vi3al7sg1 FOREIGN KEY (supplier_id)
    REFERENCES public.supplier_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product_model
    ADD CONSTRAINT fka9309xvh1lcl6ubwgq36sdnwo FOREIGN KEY (brand_id)
    REFERENCES public.brand_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product_model
    ADD CONSTRAINT fkc8fgrbgh4j89d3p2lp7orfiva FOREIGN KEY (category_id)
    REFERENCES public.category_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product_tags
    ADD CONSTRAINT fkeo41twep44vhulgdqk04tmo5q FOREIGN KEY (product_id)
    REFERENCES public.product_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product_tags
    ADD CONSTRAINT fkp6rydgkuf1e16chcuf2k9p1eh FOREIGN KEY (tag_id)
    REFERENCES public.tag_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.review_model
    ADD CONSTRAINT fkdteliqsylgpayl0u0va014f3g FOREIGN KEY (product_id)
    REFERENCES public.product_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.review_model
    ADD CONSTRAINT fksxepqdgheewuk2kels5x3rh4u FOREIGN KEY (customer_id)
    REFERENCES public.customer_model (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_role
    ADD CONSTRAINT fkryojaj4bpgbcrlxbtdbejvwn FOREIGN KEY (user_id)
    REFERENCES public.user_model (id_user) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;